import React, { useState } from "react";
import Head from "next/head";
import Layout from "@/components/Layout";
import MapComponent from "@/components/MapComponent";
import {
  CategoryDropDown,
  CasteDropDown,
  StdDropDown,
} from "@/components/DropDown";
const demoReasons = [
  {
    reason: "Not interested in education",
    rate: 19.85,
  },
  {
    reason: "Financial constraints",
    rate: 26.27,
  },
  {
    reason: "Engaged in domestic activities",
    rate: 4.62,
  },
];

const ReasonsTab = ({ classes, reasonList }) => {
  return (
    <div className={`${classes} `}>
      <h3 className="w-full text-center py-4 text-xl tracking-wider uppercase border-b-2 border-solid border-dark">
        Reaons for Dropouts
      </h3>
      {reasonList.map((item) => {
        return (
          <div className="w-full flex flex-row mx-3 my-3">
            <div className="w-[75%] text-lg">{item.reason}</div>
            <div className="w-[25%] text-lg font-bold">{item.rate}%</div>
          </div>
        );
      })}
    </div>
  );
};

const geography = () => {
  const [category, setCategory] = useState("O");
  const [caste, setCaste] = useState("Overall");
  const [std, setStd] = useState(2);
  const [reasonList, setReasonList] = useState(demoReasons);
  const [rates, setRates] = useState([]);

  console.log(category);
  return (
    <>
      <Head>
        <title>Dropout Analysis</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="">
        <Layout classname="">
          <h2 className="text-dark text-3xl w-full text-center mt-10">
            GEOGRAPHICAL DISTRIBUTION
          </h2>
          <div className="text-light mt-10 w-[30%] flex flex-row  mr-4 justify-between">
            <CategoryDropDown category={category} setCategory={setCategory} />
            <CasteDropDown caste={caste} setCaste={setCaste} />
            <StdDropDown std={std} setStd={setStd} />
          </div>
          <div className="w-full h-[500px] mx-auto mb-10 flex flex-row ">
            <ReasonsTab
              reasonList={reasonList}
              classes="text-dark w-[30%] mr-4 border-2 border-solid border-dark"
            />

            <MapComponent
              classes="w-[70%]"
              category={category}
              caste={caste}
              std={std}
              setRates={setRates}
            />
          </div>
        </Layout>
      </div>
    </>
  );
};

export default geography;
