import React, { useEffect, useState } from "react";
import Head from "next/head";
import Layout from "@/components/Layout";
import MapComponent from "@/components/MapComponent";
import {
  CategoryDropDown,
  CasteDropDown,
  StdDropDown,
} from "@/components/DropDown";
const demoReasons = [
  {
    reason: "Not interested in education",
    rate: 19.85,
  },
  {
    reason: "Financial constraints",
    rate: 26.27,
  },
  {
    reason: "Engaged in domestic activities",
    rate: 4.62,
  },
];

const ReasonsTab = ({ classes, reasonList }) => {
  return (
    <div className={`${classes} bg-secLight dark:bg-secDark rounded-xl  `}>
      <h3 className="w-full text-center py-4 text-xl tracking-wider uppercase text-light font-bold bg-secDark dark:bg-dark   rounded-t-xl border-solid border-t-2 border-x-2 dark:border-secDark">
        Reaons for Dropouts
      </h3>

      {reasonList.map((item) => {
        return (
          <div
            key={item.id}
            className="w-[95%] flex flex-row px-5 py-4 border-b-2 border-solid border-secDark dark:border-secLight dark:text-light mx-auto"
          >
            <div className="w-[80%] text-lg">{item.reason}</div>
            <div className="w-[20%] text-lg font-bold flex items-center justify-center">
              {item.rate}%
            </div>
          </div>
        );
      })}
    </div>
  );
};

const Geography = () => {
  const [category, setCategory] = useState("O");
  const [caste, setCaste] = useState("Overall");
  const [std, setStd] = useState(2);
  const [reasonList, setReasonList] = useState(demoReasons);
  const [rates, setRates] = useState([]);

  useEffect(() => {
    // Function to fetch and parse the CSV file
    const fetchReasons = async () => {
      try {
        const response = await fetch("/data/reasons.csv");
        const text = await response.text();
        const rows = text.split("\n").slice(1); // Skip header row
        // console.log(rates);
        const reasons = rows.map((row) => {
          const [
            reason,
            boys71,
            girls71,
            overall71,
            boys75,
            girls75,
            overall75,
          ] = row.split(",");

          const getReasonRate = () => {
            if (category === "O") return overall75;
            if (category === "B") return boys75;
            if (category === "G") return girls75;
          };

          return { reason, rate: parseFloat(getReasonRate()) };
        });
        setReasonList(reasons);
      } catch (error) {
        console.error("Error fetching reasons:", error);
      }
    };

    // Call the fetchReasons function
    fetchReasons();
  }, [category]);

  return (
    <>
      <Head>
        <title>Dropout Analysis</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="">
        <Layout classname="">
          <div className="flex flex-row justify-between h-[100px] items-center">
            <h2 className="text-acc dark:text-alt text-3xl text-left  font-extrabold ">
              GEOGRAPHICAL DISTRIBUTION
            </h2>
            <div className="text-light mt-2 w-[30%] flex flex-row  mr-4 justify-between">
              <CategoryDropDown category={category} setCategory={setCategory} />
              <CasteDropDown caste={caste} setCaste={setCaste} />
              <StdDropDown std={std} setStd={setStd} />
            </div>
          </div>

          <div className="w-full h-[650px] mx-auto mb-10 flex flex-row ">
            <ReasonsTab
              reasonList={reasonList}
              classes="text-dark w-[30%] mr-4 "
            />

            <MapComponent
              classes="w-[70%]"
              category={category}
              caste={caste}
              std={std}
              setRates={setRates}
              rates={rates}
            />
          </div>
        </Layout>
      </div>
    </>
  );
};

export default Geography;
