import Head from "next/head";
import { Inter } from "next/font/google";
import Image from "next/image";
import React, { useEffect } from "react";
import Layout from "@/components/Layout";
import Banner from "@/assets/banner.png";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Dropout Analysis</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="w-full text-dark">
        <Layout classname="!m-0 h-[calc(100vh-69px)] flex flex-row items-center justify-center">
          {/* <Layout classname="!m-0 h-[100vh] flex flex-row items-center justify-center"> */}
          <div className="w-[50%] h-full flex flex-col justify-center items-center">
            <h1 className="text-8xl tracking-wider mb-10 text-center">
              OUR MOTIVE
            </h1>
            <p className=" w-[60%] text-xl text-center mb-10 ">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Enim eos
              maiores quo eveniet rerum cupiditate, vitae, labore recusandae
              fuga officiis esse et reprehenderit alias voluptate, neque animi
              tempora quaerat rem.
            </p>
            <div className="flex flex-row">
              <Link
                href="/geography"
                className="py-4 px-6 mx-4 flex items-center justify-center text-2xl border-2 border-solid border-dark"
              >
                View Map
              </Link>
              <Link
                href="/"
                className="py-4 px-6 mx-4 flex items-center justify-center text-2xl text-light bg-dark"
              >
                Learn More
              </Link>
            </div>
          </div>
          <div className="w-[50%] h-full flex flex-row items-center justify-center">
            <Image
              priority
              src={Banner}
              alt="Gujarat"
              className="w-[80%] h-auto"
            />
          </div>
        </Layout>
      </div>
    </>
  );
}
